apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: gitopsworkshop
  region: us-west-2

nodeGroups:
  - name: ng-1
    instanceType: m5.large
    desiredCapacity: 1
    iam:
      withAddonPolicies:
        albIngress: true
        appMesh: true
        xRay: true
        cloudWatch: true